### ISSUE TITLE
[P0][Feature] 旅途管理 - 批量新增旅途頁面更新

### ISSUE THREAD

**Issue by sh1un** [Pago-TW/pago-frontend#27]
# Description
## User Story
```

角色：身為 代購者 
需求：我想要 在一次發佈好我這個旅途會行經的城市
價值：因此我可以 減少發佈的次數，不會因為我經過多個城市就要重複創建多次旅途

接受條件：
Given 代購者將的旅途將行經三個以上城市 且 日期是連貫的，並已經登入(1.2)
When 代購者點擊創建旅途
AND 代購者新增旅途(出發地、目的地、抵達時間)
Then 代購者批量發佈旅途成功，進入「旅途列表」(3.2.1)

優先順序: 1

```

## Figma
https://www.figma.com/file/ULkgCRqrxngEVoeRzATmJx/Pago---Mockup?type=design&node-id=4222-56959&mode=design&t=WrLazrX3Gpm56Esb-0

![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/4aee2a54-262a-43b5-a4f0-33b37400ff46)

## API endpoint: 

Batch Create Trip: [POST /trips/batch](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-421a5bf7-68c7-4a34-9fe0-706eb35e7db2?active-environment=67a1dc2f-d1b8-4c52-b596-50428a91c743)

## **Additional context**
[專題例行會議 - 20230804](https://www.dropbox.com/scl/fi/tgmkzl7iqh2l3kgxf9j0i/20230804.paper?rlkey=r09qkes7yb24nj9trfetufhrq&dl=0)

**Comment by EnderWolf50** [comment]
hm seems like the given figma image is wrong 🤔 

however, i think 旅途管理頁面更新 has been implemented at commit 5f0091faaac4039c692a55952371002b05a9ec54 and 12df3908bf3ba473e4f2fb1360847d07c440a5e2, and 批量新增旅途頁面更新 has been implemented at commit d54f9ec703d013192374f70a14aa3358b205e23e

maybe i should open branch so i can reference branch instead of commit after this 🥴

**Comment by EnderWolf50** [comment]
@sh1un hm seems like the given figma image is wrong 🤔

however, i think 旅途管理頁面更新 has been implemented at commit https://github.com/Pago-TW/pago-frontend/commit/5f0091faaac4039c692a55952371002b05a9ec54 and https://github.com/Pago-TW/pago-frontend/commit/12df3908bf3ba473e4f2fb1360847d07c440a5e2, and 批量新增旅途頁面更新 has been implemented at commit https://github.com/Pago-TW/pago-frontend/commit/d54f9ec703d013192374f70a14aa3358b205e23e

maybe i should open branch so i can reference branch instead of commit after this 🥴

**Comment by sh1un** [comment]
@EnderWolf50 
OK 感謝提醒!
我把 Figma 圖片換掉了
然後我也把這個 issue 狀態改成 "✅ Done"
我凌晨會在本地 run 前端上去看一下~

-

哦哦，要開分支的話也可以~
然後做完再開 PR，我再上去分支看

**Comment by EnderWolf50** [comment]
> 哦哦，要開分支的話也可以~
> 然後做完再開 PR，我再上去分支看
> (從 main 開分支)

@sh1un just to make sure, should I checkout from main or dev?

**Comment by sh1un** [comment]
@EnderWolf50 
Yes, 遵照 Gihub Flow，開分支皆以 main 為基底來開分支

![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/ddb83422-0043-4d8b-a765-c6a3a6769627)

![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/a38d7085-0533-47d1-b3aa-ba20611c3403)
